//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora
    {
        public int IdBitacora { get; set; }
        public string Controlador { get; set; }
        public string Metodo { get; set; }
        public string Mensaje { get; set; }
        public int IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Tipo { get; set; }
    }
}
