//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cumplimiento
    {
        public int IdCumplimiento { get; set; }
        public int IdPlan { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Detalles { get; set; }
    
        public virtual PlanMantenimiento PlanMantenimiento { get; set; }
    }
}
