//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cumplimiento
    {
        public int IdCumplimiento { get; set; }
        [Required]
        public int IdMantenimiento { get; set; }
        [Required]
        public System.DateTime Comienza { get; set; }
        public System.DateTime Finaliza { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> Estado { get; set; }
        [MaxLength(500)]
        public string Detalles { get; set; }
        [MaxLength(100)]
        public string Color { get; set; }

        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
