//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventarioDeRepuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioDeRepuestos()
        {
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }
    
        public int IdRepuesto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> Requisición { get; set; }
        public Nullable<int> Maximos { get; set; }
        public Nullable<int> Minimos { get; set; }
        public string Tipo { get; set; }
        public string Almacen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
