//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InventarioDeRepuestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventarioDeRepuestos()
        {
            this.Mantenimiento = new HashSet<Mantenimiento>();
        }

        public int IdRepuesto { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Range(0, 1000000000000000000)]
        public Nullable<int> Cantidad { get; set; }
        [Range(0, 1000000000000000000)]
        public Nullable<int> Requisición { get; set; }
        [Range(0, 1000000000000000000)]
        public Nullable<int> Maximos { get; set; }
        [Range(0, 1000000000000000000)]
        public Nullable<int> Minimos { get; set; }
        [MaxLength(50)]
        public string Tipo { get; set; }
        [MaxLength(50)]
        public string Almacen { get; set; }
        public double Precio { get; set; }
        public string Proveedor { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
    }
}
