//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MantenimientoDeMaquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MantenimientoDeMaquina()
        {
            this.CumplimientoMantenimiento = new HashSet<CumplimientoMantenimiento>();
            this.ParoDeMaquina = new HashSet<ParoDeMaquina>();
        }
    
        public int IdMantenimiento { get; set; }
        public string NumeroDeOrden { get; set; }
        public string NombreDeMantenimiento { get; set; }
        public string Tipo { get; set; }
        public string Fecuencia { get; set; }
        public Nullable<int> Rol { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public Nullable<int> IdMaquina { get; set; }
        public Nullable<int> IdRepuesto { get; set; }
        public string URLArchivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CumplimientoMantenimiento> CumplimientoMantenimiento { get; set; }
        public virtual InventarioDeRepuestos InventarioDeRepuestos { get; set; }
        public virtual Maquina Maquina { get; set; }
        public virtual Rol Rol1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParoDeMaquina> ParoDeMaquina { get; set; }
    }
}
