//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maquina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Maquina()
        {
            this.Mantenimiento = new HashSet<Mantenimiento>();
            this.ParoDeMaquina = new HashSet<ParoDeMaquina>();
        }
    
        public int IdMaquina { get; set; }
        public string NombreMaquina { get; set; }
        public Nullable<int> IdTipoSistema { get; set; }
        public Nullable<int> IdArea { get; set; }
        public string Codigo { get; set; }
        public string Modelo { get; set; }
        public string Proceso { get; set; }
        public Nullable<int> Cadencia { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual AreaDeMaquina AreaDeMaquina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mantenimiento> Mantenimiento { get; set; }
        public virtual TipoDeSistemaDeMaquina TipoDeSistemaDeMaquina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParoDeMaquina> ParoDeMaquina { get; set; }
    }
}
