//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ParoDeMaquina
    {
        public int IdParo { get; set; }
        [Required]

        public int IdMaquina { get; set; }
        public Nullable<int> IdMantenimiento { get; set; }
        [MaxLength(200)]
        public string Tipo { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaComienza { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }

        public virtual Mantenimiento Mantenimiento { get; set; }
        public virtual Maquina Maquina { get; set; }
    }
}
