//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSMP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanMantenimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanMantenimiento()
        {
            this.Cumplimiento = new HashSet<Cumplimiento>();
        }
    
        public int IdPlan { get; set; }
        public int IdMantenimiento { get; set; }
        public int Duracion { get; set; }
        public System.DateTime FechaDeInicio { get; set; }
        public System.DateTime FechaDeCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cumplimiento> Cumplimiento { get; set; }
        public virtual Mantenimiento Mantenimiento { get; set; }
    }
}
